### ISSUE TITLE
Term request: ligation

### ISSUE THREAD

**Issue by jakebeal** [EBI-BioModels/SBO#3]
In describing DNA assembly reactions, it would be useful to have a specific term for ligation of sequences.

It seems appropriate that this should be a child of `SBO:conversion` (SBO:0000182), as ligation is a modification of covalent bonds. It is also complementary with `SBO:cleavage` (SBO:0000178), which is the rupture of a covalent bond, whereas ligation is the formation of a covalent bond. It is also closely related to `SBO:polymerization` (SBO:0000652), except that refers to the joining of monomers to form a polymer whereas ligation is the joining of two or more polymers to form a larger polymer

Accordingly, I propose the following:

* Name: ligation
* Definition: Formation of a covalent bond resulting in the creation of a link between the ends of one or more linear polymer molecules.
* Parent: `SBO:conversion` (SBO:0000182)

Note that this definition of ligation can apply not only to DNA ligation but also the RNA ligation and protein ligation. This definition also allows for ligation to describe circularization of a single DNA fragment, joining of two DNA fragments, and joining of multiple DNA fragments.

**Comment by ntung** [comment]
Thanks, @krish193 for tackling the request. Closed the request now. @jakebeal Sorry for the late response.

**Comment by jakebeal** [comment]
Thank you - the new term looks good to me.

When is this expected to go live for use? I see that at present, the EBI lookup service is not yet showing the new term.

**Comment by NantiaL** [comment]
Hey!

There is a new version of OLS available ([OLS4](https://www.ebi.ac.uk/ols4)) in which the term is already visible after searching for **[ligation](https://www.ebi.ac.uk/ols4/ontologies/sbo/classes/http%253A%252F%252Fbiomodels.net%252FSBO%252FSBO_0000695)**.
