### ISSUE TITLE
Generalize definition of cleavage

### ISSUE THREAD

**Issue by jakebeal** [EBI-BioModels/SBO#4]
`SBO:cleavage` (SBO:0000178) is currently defined as "Rupture of a covalent bond resulting in the conversion of one physical entity into several physical entities."

For molecules with more complex topologies, however, cleavage may change the topology of the molecule without actually separating it into more than one entity. For example, a single cleavage of a circular DNA molecule results in a linear DNA molecule (and likewise for conversion of circular to linear proteins).

I would therefore propose to slightly generalize the definition to "Rupture of a covalent bond resulting in the conversion of one physical entity into several physical entities or into a physical entity of a different topological class."

**Comment by ntung** [comment]
@jakebeal the request has been resolved!

**Comment by jakebeal** [comment]
Thank you; this update looks good.
