### ISSUE TITLE
Link for the Ontology Lookup Service is not working 

### ISSUE THREAD

**Issue by shoepfl** [EBI-BioModels/SBO#6]
Dear SBO team,

The link for the Ontology Lookup Service on the main page of this GitHub repository seems to be outdated.

'SBO terms can be browsed through the Ontology Lookup Service (OLS) webpage [https://www.ebi.ac.uk/ols/ontologies/sbo.](https://www.ebi.ac.uk/ols/ontologies/sbo.%C2%A0)

It leads me to a site with the message:
Something went wrong! Please contact ols-support@ebi.ac.uk to report any bugs or give feedback.

Cause unknown (no exception details available)

This should be a quick fix and would improve the user experience a lot.

Thanks and best,

Sebastian

**Comment by ntung** [comment]
Hi Sebastian,

Thank you for your ticket. 
I have fixed the link to the Ontology Lookup Service. It should be fine now.
Please check and let us know.

Best,

**Comment by shoepfl** [comment]
Dear Tung,

yes now it works like a charm - thanks for the fix.

Best,
Sebastian
